### ISSUE TITLE
CSScomb throws error on scss file

### ISSUE THREAD

**Issue by smlombardi** [bruce/atom-csscomb#17]
Specifically, on this block of sass:

````
// [converter] $parent hack
@mixin text-emphasis-variant($parent, $color) {
  #{$parent} {
    color: $color;
  }
  a#{$parent}:hover {
    color: darken($color, 10%);
  }
}
````
Atom .172, csscomb 0.1.2

stack track:
````
Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #320
  at Object.Comb.processString (/Users/stevelombardi/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:205:19)
  at /Users/stevelombardi/.atom/packages/csscomb/lib/csscomb.coffee:44:19
  at Array.forEach (native)
  at csscomb (/Users/stevelombardi/.atom/packages/csscomb/lib/csscomb.coffee:41:10)
  at atom-text-editor.<anonymous> (/Users/stevelombardi/.atom/packages/csscomb/lib/csscomb.coffee:11:7)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)
`````

**Comment by stramel** [comment]
Please try the latest release to see if this is still an issue. Thanks!
