### ISSUE TITLE
Uncaught Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #5

### ISSUE THREAD

**Issue by alem0lars** [bruce/atom-csscomb#19]
Steps to reproduce:

1. I tried to execute "CssComb: Run" in the following file:
```
@charset "utf-8";

// Apply styles for the page approach.
@mixin apply-page-approach($ns) {
  html##{$ns} > body.approach {
  }
}
```
And I got the error below.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [csscomb](https://github.com/bruce/atom-csscomb) package, v0.1.2

### Stack Trace

Uncaught Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #5

```
At /Users/alem0lars/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:205

Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #5
  at Object.Comb.processString (/Users/alem0lars/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:205:19)
  at /Users/alem0lars/.atom/packages/csscomb/lib/csscomb.coffee:44:19
  at Array.forEach (native)
  at csscomb (/Users/alem0lars/.atom/packages/csscomb/lib/csscomb.coffee:41:10)
  at atom-text-editor.<anonymous> (/Users/alem0lars/.atom/packages/csscomb/lib/csscomb.coffee:11:7)
  at atom-text-editor.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -1:58.9 css-comb:comb (atom-text-editor.editor)
     -1:57.4 core:select-all (atom-text-editor.editor)
     -1:55.0 command-palette:toggle (atom-text-editor.editor)
     -1:52.9 core:confirm (atom-text-editor.editor.mini)
     -1:52.9 css-comb:comb (atom-text-editor.editor)
     -1:51.2 core:save (atom-text-editor.editor)
     -1:37.9 core:close (atom-text-editor.editor)
     -1:09.0 settings-view:open (atom-text-editor.editor)
     -0:51.8 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
     -0:50.0 core:confirm (atom-text-editor.editor.mini)
     -0:39.5 core:copy (div.settings-view.pane-item)
     -0:14.7 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -0:11.7 csscomb:run (atom-text-editor.editor)
  4x -0:08.9 core:save (atom-text-editor.editor)
     -0:02.8 core:close (atom-text-editor.editor)
     -0:00.9 csscomb:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "/Users/alem0lars/Develop"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
atom-color-highlight, v3.0.6
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.3
autocomplete-snippets, v1.0.1
csscomb, v0.1.2
editorconfig, v0.3.0
file-icons, v1.4.8
highlight-selected, v0.7.0
javascript-snippets, v1.0.0
language-gitignore, v0.1.1
language-haml, v0.15.0
language-lisp, v0.1.1
linter, v0.11.1
linter-coffeelint, v0.1.7
linter-csslint, v0.0.11
linter-erb, v0.0.3
linter-haml, v0.1.0
linter-jshint, v0.1.0
linter-lua, v0.1.3
linter-rubocop, v0.2.1
linter-ruby, v0.1.4
linter-scss-lint, v0.0.11
minimap, v4.1.3
minimap-color-highlight, v4.0.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-selection, v3.1.1
project-manager, v1.15.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by stramel** [comment]
This seems to be an issue with how CSScomb is handling the parsing. If you don't mind creating an issue over there that would be great!
