### ISSUE TITLE
Uncaught Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #53

### ISSUE THREAD

**Issue by Stoyvo** [bruce/atom-csscomb#24]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [csscomb](https://github.com/bruce/atom-csscomb) package, v0.1.2

### Stack Trace

Uncaught Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #53

```
At C:\Users\stoyvo\.atom\packages\csscomb\node_modules\csscomb\lib\csscomb.js:205

Error: Parsing error at undefined: Please check the validity of the CSS block starting from the line #53
  at Object.Comb.processString (C:\Users\stoyvo\.atom\packages\csscomb\node_modules\csscomb\lib\csscomb.js:205:19)
  at C:\Users\stoyvo\.atom\packages\csscomb\lib\csscomb.coffee:44:19
  at Array.forEach (native)
  at csscomb (C:\Users\stoyvo\.atom\packages\csscomb\lib\csscomb.coffee:41:10)
  at atom-text-editor.<anonymous> (C:\Users\stoyvo\.atom\packages\csscomb\lib\csscomb.coffee:11:7)
  at atom-text-editor.handler (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\src\command-registry.js:157:19)
  at EventEmitter.<anonymous> (C:\Users\stoyvo\AppData\Local\atom\app-0.189.0\resources\app\src\window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -3:16.5 core:paste (atom-text-editor.editor.mini)
     -3:15.0 core:confirm (atom-text-editor.editor.mini)
     -2:58.5 core:move-right (atom-text-editor.editor.mini)
     -2:58.2 core:delete (atom-text-editor.editor.mini)
     -2:56.4 core:confirm (atom-text-editor.editor.mini)
     -2:27.4 core:paste (atom-text-editor.editor.mini)
     -2:26.9 core:confirm (atom-text-editor.editor.mini)
     -2:00.6 core:paste (atom-text-editor.editor.mini)
     -2:00.2 core:confirm (atom-text-editor.editor.mini)
     -1:31.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:04.7 vim-mode:move-right (atom-text-editor.editor)
     -1:03.5 core:save (atom-text-editor.editor)
  2x -1:02.9 vim-mode:move-right (atom-text-editor.editor)
  2x -1:00.9 vim-mode:reset-command-mode (atom-text-editor.editor)
     -0:18.8 dev-live-reload:reload-all (atom-text-editor.editor)
     -0:08.7 csscomb:run (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "projectHome": "\\\\UBUNTU\\www",
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "git-diff",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-less",
      "language-make",
      "language-objective-c",
      "language-perl",
      "language-property-list",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-toml",
      "language-yaml",
      "metrics",
      "autocomplete",
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
color-picker, v1.5.0
csscomb, v0.1.2
csslint, v1.0.4
editor-stats, v0.17.0
editorconfig, v0.3.3
jshint, v1.3.0
minimap, v4.7.5
tabs-to-spaces, v0.9.2

# Dev
No dev packages
```

**Comment by stramel** [comment]
Please try the latest release to see if this is still an issue. Thanks!
