### ISSUE TITLE
Failed to activate the csscomb package

### ISSUE THREAD

**Issue by olegshilov** [bruce/atom-csscomb#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [csscomb](https://github.com/bruce/atom-csscomb) package, v0.1.2

### Stack Trace

Failed to activate the csscomb package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/olegshilov/.atom/packages/csscomb/lib/csscomb.coffee:15:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app/src/config.js:298:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/olegshilov/Documents"
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
color-picker, v1.7.0
csscomb, v0.1.2
emmet, v2.3.8
file-icons, v1.5.4
language-jade, v0.4.0
language-liquid, v0.2.0
linter, v0.12.0
linter-coffeelint, v0.2.1
linter-csslint, v0.0.11
linter-jscs, v1.10.0
minimap, v4.7.6
minimap-git-diff, v4.1.2

# Dev
No dev packages
```

**Comment by stramel** [comment]
Please try the latest release to see if this is still an issue and if it is, add steps to reproduce. Thanks!

**Comment by olegshilov** [comment]
@stramel thx. after update all works fine.
