### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by screeny05** [bruce/atom-csscomb#26]
### Steps to reproduce
1. I tried running the Plugin over my file `x.css`:
```css
.sprite-application--arrow{background-position:0 0!important}
```

**Atom Version**: 0.187.0
**System**: linux 3.13.0-46-generic
**Thrown From**: [csscomb](https://github.com/bruce/atom-csscomb) package, v0.1.2

### Stack Trace

Uncaught TypeError: Cannot read property '1' of undefined

```
At /home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/options/vendor-prefix-align.js:181

TypeError: Cannot read property '1' of undefined
  at /home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/options/vendor-prefix-align.js:181:54
  at Object.<anonymous> (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/options/vendor-prefix-align.js:74:13)
  at Array.forEach (native)
  at Object.module.exports._walk (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/options/vendor-prefix-align.js:68:14)
  at Object.module.exports.process (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/options/vendor-prefix-align.js:180:14)
  at Object.<anonymous> (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:182:25)
  at Array.forEach (native)
  at Object.Comb.processNode (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:170:14)
  at Object.<anonymous> (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:188:18)
  at Array.forEach (native)
  at Object.Comb.processNode (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:170:14)
  at Object.<anonymous> (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:188:18)
  at Array.forEach (native)
  at Object.Comb.processNode (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:170:14)
  at Object.<anonymous> (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:159:18)
  at Array.forEach (native)
  at Object.Comb.processTree (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:158:24)
  at Object.Comb.processString (/home/slanger/.atom/packages/csscomb/node_modules/csscomb/lib/csscomb.js:210:21)
  at /home/slanger/.atom/packages/csscomb/lib/csscomb.coffee:44:19
  at Array.forEach (native)
  at csscomb (/home/slanger/.atom/packages/csscomb/lib/csscomb.coffee:41:10)
  at atom-text-editor.<anonymous> (/home/slanger/.atom/packages/csscomb/lib/csscomb.coffee:11:7)
  at atom-text-editor.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:246:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -1:56.0 core:confirm (atom-text-editor.editor.mini)
     -1:42.3 core:select-all (atom-text-editor.editor)
     -1:40.8 editor:copy-path (atom-text-editor.editor)
     -1:37.3 core:select-all (atom-text-editor.editor)
     -1:35.9 command-palette:toggle (atom-text-editor.editor)
     -1:33.7 core:confirm (atom-text-editor.editor.mini)
     -1:33.1 csscomb:run (atom-text-editor.editor)
     -1:23.1 core:select-all (atom-text-editor.editor)
  3x -1:22.5 csscomb:run (atom-text-editor.editor)
     -0:36.1 core:copy (atom-text-editor.editor)
  4x -0:33.1 csscomb:run (atom-text-editor.editor)
     -0:04.4 core:copy (atom-text-editor.editor)
     -0:03.9 application:new-file (atom-text-editor.editor)
     -0:02.7 core:paste (atom-text-editor.editor.is-focused)
     -0:01.4 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.8 csscomb:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false,
    "disabledPackages": [
      "symbols-view",
      "build",
      "racer"
    ],
    "themes": [
      "outlander-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "csscomb": {
    "remove-empty-rulesets": true,
    "always-semicolon": true,
    "color-case": "lower",
    "color-shorthand": true,
    "element-case": "lower",
    "sort-order-fallback": "abc",
    "space-before-colon": "",
    "space-after-colon": " ",
    "space-before-combinator": " ",
    "space-after-combinator": " ",
    "space-between-declarations": "\n",
    "space-before-opening-brace": " ",
    "space-after-opening-brace": "\n",
    "space-after-selector-delimiter": "\n",
    "space-before-selector-delimiter": "",
    "space-before-closing-brace": "\n",
    "strip-spaces": true,
    "unitless-zero": true,
    "vendor-prefix-align": true
  }
}
```

### Installed Packages

```coffee
# User
atom-cli-diff, v0.11.0
atom-color-highlight, v3.0.8
atom-ctags, v2.6.1
autocomplete-css, v0.6.0
autocomplete-plus, v2.7.1
csscomb, v0.1.2
docblockr, v0.6.3
editorconfig, v0.3.3
file-icons, v1.5.4
highlight-selected, v0.9.1
language-expressionengine, v0.2.3
language-html-swig, v1.4.0
language-javascript-semantic, v0.1.0
language-rust, v0.4.3
language-smarty-php, v0.5.0
less-than-slash, v0.6.0
linter, v0.12.0
linter-php, v0.0.12
minimap, v4.7.6
minimap-highlight-selected, v4.2.0
outlander-ui, v1.0.2
php-twig, v3.0.0
project-palette-finder, v2.4.16
regex-railroad-diagram, v0.7.4

# Dev
No dev packages
```

**Comment by stramel** [comment]
Please check this with the latest release. I was unable to reproduce using the latest code.
